import React, { Component } from 'react';
import {Animated, Button, StyleSheet, Text, View} from 'react-native';
import {Audio} from "expo-av";

export default class Assignment1Component extends Component {

    constructor(props) {
        super(props);
        this.playbackInstance = null;
        this.state = {
            opacity: new Animated.Value(0),
            opacityGreenLeft: new Animated.Value(0),
            opacityGreenRight: new Animated.Value(0),
            opacityRedJays1: new Animated.Value(0),
            opacityRedJays2: new Animated.Value(0),
            opacityRedJays3: new Animated.Value(0),
            opacityRedJays4: new Animated.Value(0),
            opacityH1: new Animated.Value(0),
            opacityA1: new Animated.Value(0),
            opacityP1: new Animated.Value(0),
            opacityP2: new Animated.Value(0),
            opacityY1: new Animated.Value(0),
            opacityH2: new Animated.Value(0),
            opacityO1: new Animated.Value(0),
            opacityL1: new Animated.Value(0),
            opacityI1: new Animated.Value(0),
            opacityD1: new Animated.Value(0),
            opacityA2: new Animated.Value(0),
            opacityY2: new Animated.Value(0),
            opacityS1: new Animated.Value(0),
            opacityTree1: new Animated.Value(0),
            opacityTree2: new Animated.Value(0),
            opacityTree3: new Animated.Value(0),
            opacityTree4: new Animated.Value(0),
            opacityTree5: new Animated.Value(0),
            opacityTree6: new Animated.Value(0),
            opacityTree7: new Animated.Value(0),
            opacityTree8: new Animated.Value(0),
            opacityTree9: new Animated.Value(0),
            opacityTree10: new Animated.Value(0),
            opacityTree11: new Animated.Value(0),
            opacityTree12: new Animated.Value(0),
            opacityTree13: new Animated.Value(0),
            opacityTree14: new Animated.Value(0),
            opacityTree15: new Animated.Value(0),
            opacityTree16: new Animated.Value(0),
            opacityTree17: new Animated.Value(0),
            opacityTree18: new Animated.Value(0),
            opacityTree19: new Animated.Value(0),
            opacityTree20: new Animated.Value(0),
            opacityTree21: new Animated.Value(0),
            opacityTree22: new Animated.Value(0),
        }
    }

    componentDidMount() {
        Audio.setAudioModeAsync({
            allowsRecordingIOS: false,
            interruptionModeIOS: Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
            playsInSilentModeIOS: true,
            shouldDuckAndroid: true,
            interruptionModeAndroid: Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
            playThroughEarpieceAndroid: false,
            staysActiveInBackground: true
        });

        this._loadNewPlaybackInstance(true);

        Animated.sequence([
            Animated.delay(500),
            Animated.parallel([
                Animated.sequence([
                    this.guitarVerse(),
                    Animated.delay(1500),
                    this.guitarVerse(),
                ]),
                Animated.sequence([
                    this.pianoVerse(),
                    this.pianoInterludeUp(),
                    this.pianoVerse(),
                    this.pianoInterludeUpAndDown(),
                    this.chorus1(),
                    this.pianoInterludeUp2(),
                    this.chorus1(),
                    this.pianoInterludeUp3(),
                    this.pianoInterludeUp3(),
                    this.preChorus2(),
                    this.chorus2()
                ]),
            ])
        ]).start(() => {this.playbackInstance.stopAsync()});
    }

    blink(object, upDuration = 5, downDuration = 95) {
        return Animated.sequence([
            Animated.timing(object, {toValue: 1, duration: upDuration}),
            Animated.timing(object, {toValue: 0, duration: downDuration}),
        ]);
    }

    preChorus2() {
        return Animated.sequence([
            Animated.delay(350),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(150),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(250),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(250),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(250),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(250),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(250),
        ]);
    }

    pianoInterludeUp3() {
        const interval = 75;
        return Animated.sequence([
            Animated.delay(interval*3 + 175),
            Animated.parallel([
                this.blink(this.state.opacityTree2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
        ]);
    }

    pianoInterludeUp2() {
        const interval = 70
        return Animated.sequence([
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
            ]),
        ]);
    }

    chorus1() {
        const interval = 10;
        return Animated.sequence([
            Animated.parallel([
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
        ]);
    }

    chorus2() {
        const interval = 10;
        return Animated.sequence([
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree20),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree19),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityTree1),
                this.blink(this.state.opacityTree2),
                this.blink(this.state.opacityTree3),
                this.blink(this.state.opacityTree4),
                this.blink(this.state.opacityTree5),
                this.blink(this.state.opacityTree6),
                this.blink(this.state.opacityTree7),
                this.blink(this.state.opacityTree8),
                this.blink(this.state.opacityTree9),
                this.blink(this.state.opacityTree10),
                this.blink(this.state.opacityTree11),
                this.blink(this.state.opacityTree12),
                this.blink(this.state.opacityTree13),
                this.blink(this.state.opacityTree14),
                this.blink(this.state.opacityTree15),
                this.blink(this.state.opacityTree16),
                this.blink(this.state.opacityTree17),
                this.blink(this.state.opacityTree18),
                this.blink(this.state.opacityTree19),
                this.blink(this.state.opacityTree20),
                this.blink(this.state.opacityTree21),
                this.blink(this.state.opacityTree22),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
                this.blink(this.state.opacityRedJays1),
                this.blink(this.state.opacityRedJays2),
                this.blink(this.state.opacityRedJays3),
                this.blink(this.state.opacityRedJays4),
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
        ]);
    }

    pianoInterludeUp() {
        const interval = 70;
        return Animated.sequence([
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP1),
                this.blink(this.state.opacityP2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityI1),
                this.blink(this.state.opacityD1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityS1),
            ]),
        ])
    }

    pianoInterludeUpAndDown() {
        const interval = 70;
        return Animated.sequence([
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityD1),
                this.blink(this.state.opacityA2),
                this.blink(this.state.opacityY2),
                this.blink(this.state.opacityS1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityO1),
                this.blink(this.state.opacityL1),
                this.blink(this.state.opacityI1),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityP2),
                this.blink(this.state.opacityY1),
                this.blink(this.state.opacityH2),
            ]),
            Animated.delay(interval),
            Animated.parallel([
                this.blink(this.state.opacityH1),
                this.blink(this.state.opacityA1),
                this.blink(this.state.opacityP1),
            ]),
        ])
    }

    pianoVerse() {
        const interval = 70;
        return Animated.sequence([
            this.blink(this.state.opacityRedJays1),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays2),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays3),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays4),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays1),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays2),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays3),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays4),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays1),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays2),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays3),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays4),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays1),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays2),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays3),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays4),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays1),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays2),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays3),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays4),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays1),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays2),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays3),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays4),
            Animated.delay(interval),
            this.blink(this.state.opacityRedJays1),
        ])
    }

    guitarVerse() {
        const interval = 25;
        const bigInterval = 350;
        return Animated.sequence([
            this.blink(this.state.opacity),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(bigInterval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
            ]),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(bigInterval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
            ]),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(bigInterval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
            ]),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(bigInterval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
            ]),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(bigInterval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
            ]),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(interval),
            this.blink(this.state.opacity),
            Animated.delay(bigInterval),
            Animated.parallel([
                this.blink(this.state.opacity),
                this.blink(this.state.opacityGreenLeft),
                this.blink(this.state.opacityGreenRight),
            ]),
            Animated.delay(interval),
            this.blink(this.state.opacity),
        ]);
    }

    async _loadNewPlaybackInstance(playing) {
        if (this.playbackInstance != null) {
            await this.playbackInstance.unloadAsync();
            this.playbackInstance.setOnPlaybackStatusUpdate(null);
            this.playbackInstance = null;
        }
        const source = require('./assets/song.mp3');
        const initialStatus = {
            shouldPlay: true,
            rate: 1.0,
            shouldCorrectPitch: true,
            volume: 1.0,
            isMuted: false
        };
        const { sound, status } = await Audio.Sound.createAsync(
            source,
            initialStatus
        );
        this.playbackInstance = sound;
        this.playbackInstance.setIsLoopingAsync(true);
        this.playbackInstance.playAsync();
    }

    componentWillUnmount() {
        this.playbackInstance.unloadAsync();
//  Check Your Console To verify that the above line is working
        console.log('unmount');
    }

    render() {
        return (
            <View style={styles.container}>
                <Animated.View style={{borderTopColor: 'white', borderTopWidth: 10, width: 450, opacity: this.state.opacity}} />
                <View style={{flexDirection: 'row', paddingTop: 10, paddingBottom: 20}}>
                    <Animated.View style={[styles.circle, {opacity: this.state.opacityGreenLeft}]} />
                    <Animated.Text style={[styles.happyHolidays, {color: 'red', opacity: this.state.opacityH1}]}>H</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'green', opacity: this.state.opacityA1}]}>A</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'white', opacity: this.state.opacityP1}]}>P</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'red', opacity: this.state.opacityP2}]}>P</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'green', opacity: this.state.opacityY1}]}>Y</Animated.Text>
                    <Text> </Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'white', opacity: this.state.opacityH2}]}>H</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'red', opacity: this.state.opacityO1}]}>O</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'green', opacity: this.state.opacityL1}]}>L</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'white', opacity: this.state.opacityI1}]}>I</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'red', opacity: this.state.opacityD1}]}>D</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'green', opacity: this.state.opacityA2}]}>A</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'white', opacity: this.state.opacityY2}]}>Y</Animated.Text>
                    <Animated.Text style={[styles.happyHolidays, {color: 'red', opacity: this.state.opacityS1}]}>S</Animated.Text>
                    <Animated.View style={[styles.circle, {opacity: this.state.opacityGreenRight}]} />
                </View>
                <Animated.View style={{borderTopColor: 'white', borderTopWidth: 10, width: 450, opacity: this.state.opacity}}/>
                <View style={{flexDirection: 'row', marginTop: 30}}>
                    <Animated.View style={{flexDirection: 'column', opacity: this.state.opacityRedJays1}}>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                    </Animated.View>
                    <Animated.View style={{flexDirection: 'column', opacity: this.state.opacityRedJays2}}>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                    </Animated.View>
                    <Animated.View style={{flexDirection: 'column', opacity: this.state.opacityRedJays3}}>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                    </Animated.View>
                    <Animated.View style={{flexDirection: 'column', opacity: this.state.opacityRedJays4}}>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                        <Text style={[styles.text, styles.redJays]}>J</Text>
                    </Animated.View>
                    <View style={{flexDirection: 'column', marginLeft: 50}}>
                        <View style={{flexDirection: 'row', justifyContent: 'center',}}>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree1}]}>#</Animated.Text>
                        </View>
                        <View style={{flexDirection: 'row', justifyContent: 'center',}}>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree2}]}>#</Animated.Text>
                        </View>
                        <View style={{flexDirection: 'row', justifyContent: 'center',}}>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree3}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree4}]}>#</Animated.Text>
                        </View>
                        <View style={{flexDirection: 'row', justifyContent: 'center',}}>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree5}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree6}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree7}]}>#</Animated.Text>
                        </View>
                        <View style={{flexDirection: 'row', justifyContent: 'center',}}>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree8}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree9}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree10}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree11}]}>#</Animated.Text>
                        </View>
                        <View style={{flexDirection: 'row', justifyContent: 'center',}}>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree12}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree13}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree14}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree15}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree16}]}>#</Animated.Text>
                        </View>
                        <View style={{flexDirection: 'row', justifyContent: 'center',}}>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree17}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree18}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree19}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree20}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree21}]}>#</Animated.Text>
                            <Animated.Text style={[styles.trees, {opacity: this.state.opacityTree22}]}>#</Animated.Text>
                        </View>
                    </View>
                </View>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'black',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column'
    },
    happyHolidays: {
        fontSize: 30,
        fontWeight: 'bold',
        marginTop: 5
    },
    redJays: {
        color: 'red',
        fontSize: 45,
        transform: [{rotateX: '180deg'}, {rotateY: '180deg'}],
        margin: 3,
    },
    trees: {
        color: 'white',
        fontSize: 25,
        marginLeft: 3,
        marginRight: 3
    },
    circle: {
        opacity: 0,
        width: 50,
        height: 50,
        borderRadius: 25,
        borderWidth: 10,
        borderColor: 'green',
        marginLeft: 40,
        marginRight: 40,
    },
});
